# Generated by Django 4.1.1 on 2022-09-09 12:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальная строка')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд/Производитель')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('code', models.CharField(db_index=True, default=None, help_text='Код товара должен быть в числовом виде формата: <em>000000</em>.', max_length=16, unique=True, verbose_name='Код товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('attributes', models.JSONField(blank=True, help_text='используйте JSON-формат', null=True, verbose_name='Атрибуты')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен к покупке')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='User')),
                ('official_link', models.URLField(unique=True, verbose_name='Ссылка на оф. ресурс')),
                ('proof_link', models.URLField(unique=True, verbose_name='Пруф ссылка')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('map', models.CharField(blank=True, help_text='При импорте необходимо указать атрибут ширины 100%!', max_length=512, null=True, verbose_name='Карта')),
                ('phone_number', models.CharField(help_text='Номер телефона должен иметь формат: +79999999999', max_length=13, validators=[django.core.validators.RegexValidator(message="Номер телефона должен иметь формат: '+79999999999' ", regex='^\\+?1?\\d{9,13}$')], verbose_name='Номер тел. магазина')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('weekday_from', models.TimeField(default=None, help_text='Начало рабочего дня по будням', verbose_name='Пн-пт с:')),
                ('weekday_to', models.TimeField(default=None, help_text='Конец рабочего дня по будням', verbose_name='Пн-пт до:')),
                ('saturday_from', models.TimeField(blank=True, default=None, help_text='Начало рабочего дня в субботу', verbose_name='Сб с:')),
                ('saturday_to', models.TimeField(blank=True, default=None, help_text='Конец рабочего дня в субботу', verbose_name='Сб до:')),
                ('sunday_from', models.TimeField(blank=True, default=None, help_text='Начало рабочего дня в воскресенье', verbose_name='Вс с:')),
                ('sunday_to', models.TimeField(blank=True, default=None, help_text='Конец рабочего дня в воскресенье', verbose_name='Вс до:')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность магазина')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(auto_now=True, null=True, verbose_name='Дата ред-ия записи')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Иконка должна быть размерами 27х27 png', upload_to='product_photos/', verbose_name='Фотография товара')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основная фотография')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.product', verbose_name='Товар')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='seller.seller', verbose_name='Продавец'),
        ),
    ]
