# Generated by Django 4.1.1 on 2022-09-09 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category_tree', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='products', to='category_tree.productcategory', verbose_name='Категория->Подкатегория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=None, help_text='Заполняется автоматически', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='seller.seller', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Уникальная строка'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
        ),
    ]
